            - name: Generate macOS Installer
  # You may pin to the exact commit or the version.
  # uses: akiojin/generate-mac-installer-github-action@2b665a3fa23e4ced931708ae7a94e280d10e6651
  uses: akiojin/generate-mac-installer-github-action@v0.1.1
  with:
    # Specifies the output directory. If omitted, runner.temp is set.

    output-directory: # optional, default is ${{ runner.temp }}
    # The root path of the directory containing the set of resources to be bundled.

    root-directory: # optional
    # Specify the relative path of *.app to be placed under the directory specified in 'root-directory' as the base point.

    bundle-path: 
    # Specify the application ID.

    identifier: 
    # Specifies the version of the package to be created. If omitted, github.run_numer is set.

    version:  github.run_numer
    # The directory where the package is to be installed. If omitted, '/Applications' is specified.

    install-location: # optional, default is /Applications
          
