name: Generate macOS Installer

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pkg:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyserial pyvolume

      # Build a macOS .app bundle (required by the installer action)
      - name: Build macOS app bundle
        run: |
          pyinstaller --windowed --name SoloListener --hidden-import serial.tools.list_ports listener/main.py
          ls -la dist

      - name: Generate macOS Installer
        uses: akiojin/generate-mac-installer-github-action@v0.1.1
        with:
          root-directory: dist
          bundle-path: SoloListener.app
          identifier: com.solo.board.listener
          version: ${{ github.run_number }}
          output-directory: installers

      - name: Verify installers directory
        run: |
          ls -la installers

      - name: Commit and push installers to main
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add installers/
          git commit -m "Add macOS installer (run ${{ github.run_number }}) [skip ci]" || echo "No changes"
          git push
