name: Generate macOS Installer

on:
  push:
    branches:
      'main'

jobs:
  pkg:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyserial pyvolume

      # Build a macOS .app bundle (required by the installer action)
      - name: Build macOS app bundle
        run: |
          pyinstaller --windowed --name SoloListener --hidden-import serial.tools.list_ports listener/main.py
          ls -la dist

      - name: Generate macOS Installer
        uses: akiojin/generate-mac-installer-github-action@v0.1.1
        with:
          root-directory: dist
          bundle-path: SoloListener.app
          identifier: com.solo.board.listener
          version: ${{ github.run_number }}
          output-directory: ${{ runner.temp }}
          # install-location: /Applications   # optional

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: installers/**
          if-no-files-found: error
